### ISSUE TITLE
Codes in C++

### ISSUE THREAD

**Issue by mish24** [gwtw/ts-fibonacci-heap#10]
Hi!
I am sorry for opening an issue here. I have been following the stuff on Growing with the web since a long time. I am primarily strong in C++. If its okay with you, I'd like to contribute the code for the algorithms in C++. I already have the code for Fibonacci Heap, Binomial Heap and RB trees. 

Thanks

**Comment by Tyriar** [comment]
Wasn't even watching my own repo 🤷‍♂ 

If you're still interested in this I can setup a cpp-fibonacci-heap repo to contribute to, I've been wanting to expand into C++ but not know how to set up a nice minimal build with tests was blocking me.

**Comment by Tyriar** [comment]
Closing out as I won't have time for this, I think it's best to keep `gwtw` as my own code as a companion to my blog
