### ISSUE TITLE
module not registered in NPM

### ISSUE THREAD

**Issue by techdrushim** [gwtw/ts-fibonacci-heap#11]
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@tyriar%2ffibonacci-heap - Not found
npm ERR! 404
npm ERR! 404  '@tyriar/fibonacci-heap@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:

Please advice me ASAP

**Comment by mersanuzun** [comment]
I have same issue

**Comment by Paul1205** [comment]
It's something related to npm

https://status.npmjs.org/incidents/cksjqc1w11v5?u=1zkkzs287tq6

**Comment by dsanandiya** [comment]
Seems to be an upstream issue with scoped npm packages.
FYI: https://status.npmjs.org/

**Comment by hasangenc0** [comment]
also can't access from yarn registry
https://registry.yarnpkg.com/@tyriar/fibonacci-heap/-/fibonacci-heap-2.0.9.tgz

**Comment by hasangenc0** [comment]
> also can't access from yarn registry
> https://registry.yarnpkg.com/@tyriar/fibonacci-heap/-/fibonacci-heap-2.0.9.tgz

it was about npm :D they fixed the issue

**Comment by Tyriar** [comment]
Phew, all good 😛
